name: MooTools-DatePicker
author: astolwijk
current: 1.17
category: Widgets
tags: [Datepicker,Calendar]
demo: http://www.monkeyphysics.com/mootools/script/2/datepicker
docs: http://www.monkeyphysics.com/mootools/script/2/datepicker